export const LANGUAGE_MAPPINGS = {
    orm: "Afaan Oromoo",
    afr: "Afrikaans",
    ase: "American Sign Language (ASL)",
    apw: "Apache",
    asf: "Auslan",
    aym: "Aymar Aru",
    ind: "Bahasa Indonesia",
    msa: "Bahasa Melayu",
    bam: "Bambara",
    tzo: "Bats'i k'op",
    bik: "Bikol",
    bis: "Bislama",
    cak: "Cakchiquel",
    cat: "Català",
    ceb: "Cebuano",
    ces: "Česky",
    cha: "Chamoru",
    nya: "Chichewa",
    cym: "Cymraeg",
    dan: "Dansk",
    deu: "Deutsch",
    nav: "Diné bizaad",
    cuk: "Dulegaya",
    yor: "Èdè Yorùbá",
    est: "Eesti",
    efi: "Efik",
    guz: "EkeGusii",
    eng: "English",
    spa: "Español",
    eus: "Euskera",
    ton: "Faka-tonga",
    fat: "Fante",
    hif: "Fiji Hindi",
    chk: "Fosun Chuuk",
    fon: "Fɔngbè",
    fra: "Français",
    smo: "Gagana Samoa",
    tvl: "gana Tuvalu",
    grn: "Guaraní (Avañe'ẽ)",
    hil: "Hiligaynon",
    hmo: "Hiri Motu",
    hmn: "Hmoob",
    hrv: "Hrvatski",
    haw: "ʻŌlelo Hawaiʻi",
    sto: "I^ethka (Yethka)",
    ibo: "Igbo",
    ilo: "Ilokano",
    nbl: "isiNdebele",
    xho: "isiXhosa",
    zul: "isiZulu",
    isl: "Íslenska",
    ita: "Italiano",
    kos: "Kahs Kosrae",
    mah: "Kajin Majōl",
    qvi: "Kichwa",
    kam: "Kikamba",
    kin: "Kinyarwanda",
    gil: "Kiribati",
    swa: "Kiswahili",
    niu: "ko e vagahau Niuē",
    hat: "Kreyòl Ayisyen",
    lav: "Latviešu",
    lit: "Lietuvių",
    lin: "Lingála",
    yua: "maayaʼ tʼàan",
    hun: "Magyar",
    pon: "Mahsen en Pohnpei",
    mlg: "Malagasy",
    mlt: "Malti",
    mam: "Mam",
    rar: "Māori Kuki Airani",
    nld: "Nederlands",
    bla: "Nitsi’powahsin",
    cag: "Nivacle",
    nor: "Norsk",
    pau: "Palauan",
    pam: "Pampango",
    pag: "Pangasinan",
    pap: "Papiamento",
    pol: "Polski",
    por: "Português (Brasil)",
    ept: "Português (Portugal)",
    kek: "Q'eqchi'",
    quh: "Quechua-Bolivia",
    quc: "Quiché",
    tah: "Reo Tahiti",
    ron: "Română",
    nso: "sePêdi",
    tsn: "Setswana",
    sna: "Shona",
    alb: "Shqip",
    ssw: "siSwati",
    slk: "Slovenčina",
    slv: "Slovenščina",
    sot: "South Sotho",
    fin: "Suomi",
    swe: "Svenska",
    tgl: "Tagalog",
    mri: "Te Reo Māori",
    yap: "Thin Nu Wa'ab",
    vie: "Tiếng Việt",
    tpi: "Tok Pisin",
    lua: "Tshiluba",
    tur: "Türkçe",
    twi: "Twi",
    fij: "Vosa vakaviti",
    war: "Waray",
    quz: "Yunkay Quechua",
    ell: "Ελληνικά",
    bul: "Български",
    kaz: "Қазақ",
    mkd: "Македонски",
    mon: "Монгол",
    rus: "Русский",
    srp: "Српски",
    ukr: "Українська",
    kat: "ქართული",
    hyw: "Արեւմտահայերէն",
    hye: "Հայերեն",
    urd: "اردو",
    ara: "العربية",
    pes: "فارسی",
    amh: "አማርኛ",
    nep: "नेपाली",
    hin: "हिन्दी, हिंदी",
    ben: "বাংলা",
    tam: "தமிழ்",
    tel: "తెలుగు",
    kan: "ಕನ್ನಡ",
    sin: "සිංහල",
    tha: "ภาษาไทย",
    lao: "ພາສາລາວ",
    ksw: "ကညီလံာ်ခီၣ်ထံ",
    mya: "ဗမာစာ",
    khm: "ភាសាខ្មែរ",
    kor: "한국어",
    jpn: "日本語",
    zhs: "简体中文 - 普通话",
    zho: "繁體中文 - 國語",
    yue: "繁體中文 - 廣東話",
} as const;

export const AVAILABLE_LANGUAGES = [
    "afr",
    "alb",
    "amh",
    "apw",
    "ara",
    "ase",
    "asf",
    "aym",
    "bam",
    "ben",
    "bik",
    "bis",
    "bla",
    "bul",
    "cag",
    "cak",
    "cat",
    "ceb",
    "ces",
    "cha",
    "chk",
    "cuk",
    "cym",
    "dan",
    "deu",
    "efi",
    "ell",
    "eng",
    "ept",
    "est",
    "eus",
    "fat",
    "fij",
    "fin",
    "fon",
    "fra",
    "gil",
    "grn",
    "guz",
    "hat",
    "haw",
    "hif",
    "hil",
    "hin",
    "hmn",
    "hmo",
    "hrv",
    "hun",
    "hye",
    "hyw",
    "ibo",
    "ilo",
    "ind",
    "isl",
    "ita",
    "jpn",
    "kam",
    "kan",
    "kat",
    "kaz",
    "kek",
    "khm",
    "kin",
    "kor",
    "kos",
    "ksw",
    "lao",
    "lav",
    "lin",
    "lit",
    "lua",
    "mah",
    "mam",
    "mkd",
    "mlg",
    "mlt",
    "mon",
    "mri",
    "msa",
    "mya",
    "nav",
    "nbl",
    "nep",
    "niu",
    "nld",
    "nor",
    "nso",
    "nya",
    "orm",
    "pag",
    "pam",
    "pap",
    "pau",
    "pes",
    "pol",
    "pon",
    "por",
    "quc",
    "quh",
    "quz",
    "qvi",
    "rar",
    "ron",
    "rus",
    "sin",
    "slk",
    "slv",
    "smo",
    "sna",
    "sot",
    "spa",
    "srp",
    "ssw",
    "sto",
    "swa",
    "swe",
    "tah",
    "tam",
    "tel",
    "tgl",
    "tha",
    "ton",
    "tpi",
    "tsn",
    "tur",
    "tvl",
    "twi",
    "tzo",
    "ukr",
    "urd",
    "vie",
    "war",
    "xho",
    "yap",
    "yor",
    "yua",
    "yue",
    "zho",
    "zhs",
    "zul",
] as const;

export type AvailableLanguage = typeof AVAILABLE_LANGUAGES[number];
